### ISSUE TITLE
How to build and run examples on MacOS

### ISSUE THREAD

**Issue by codingwatching** [weigert/TinyEngine#21]
hi @weigert 
I am trying to make this awesome Engine works on macOS. I just download all required libraries and can run build all

I modify the makefile of each example to work in macOS like bellow
```
TINYLINK = -lpthread -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -framework OpenGL -lGLEW -lboost_system -lboost_filesystem
```
(Remove -lX11 and replace -lGL with -framework OpenGL)

Then I can compile and run example 1
With example 2, I have this error:

```
4.1 ATI-4.5.14
Linker Error: ERROR: 0:1: '' :  version '130' is not supported
ERROR: 0:2: '' :  #version required and missing.

Linker Error: ERROR: 0:1: '' :  version '130' is not supported
ERROR: 0:2: '' :  #version required and missing.


```
![image](https://user-images.githubusercontent.com/85933804/124722785-98378180-df34-11eb-8c42-a19a5cc5c94d.png)

If you want I can create PR after all examples run on MacOS! Thank you in advance!

**Comment by weigert** [comment]
Hi codingwatching,

Thank you for opening this issue. Your work on getting the correct linkage motivated me to finally add MacOS compatibility. This is done now.

Actually, you did everything correctly, except for the fact that MacOS OpenGL simply does not support lower versions than 330. Therefore, the shader programs had to simply be altered to have version between 330 and 410 (supported versions), including core profiles. This fixes the issue.

I have modified the makefiles from the examples to include a uname test and compile directly for mac so they don't require modification and compile correctly, and raised the minimum version to GLSL 330. Therefore, you should now be able to compile (almost) all examples and run them natively. I have tested this on a 2020 macbook air with Big Sur.


Additionally, the main README file now has instructions on how to install all dependencies directly on Mac. I tested this, and it basically ran immediately. 1. Install dependencies 2. Clone Repo 3. sudo make all 4. compile examples 5. It works!


I am working on making the interfaces slightly more elegant though, and will see if I can get all example programs compatible.

I have not found an elegant way to actually change the GLSL version based on the operating system / available GLSL versions. This could be done using a special parser in the shader class, but I am not sure if it is clunky / should be left up to the user to make sure the used GLSL versions are supported.

**Comment by weigert** [comment]
So thanks again and if you want you can open an issue on the main readme crediting yourself at the bottom of the MacOS section (e.g. credit: user codingwatching) and I'll merge the pull request so you're visible as a contributor.

**Comment by codingwatching** [comment]
@weigert That is my honor! Thank you!
