### ISSUE TITLE
Attempt at getting working on Mac M1

### ISSUE THREAD

**Issue by madasebrof** [weigert/TinyEngine#36]
See this repo...

Posting just in case anyone else want to go further with this.

https://github.com/RealLast/TinyEngineDebug

**Comment by weigert** [comment]
Hi.

I have recently been able to acquire a Mac with an M1 chip, and have merged a branch `macOS-arm64` into master which contains:
- New README.md for install instructions on Mac
- Updated Make rules (you correctly stated in #26 that you simply have reference the home-brew include folder)

The other main fix is basically upgrading the gcc version.
There is also a segfault when doing specific texture operations and specific glVertexAttribPointer calls.

There are still some issues with some driver stuff, so a number of examples won't work:
- Example 6: Some very strange driver issues which I need to investigate
- All compute shader examples
- Some SSBO shader examples (some work, some don't, even though theoretically none should work)

Thank you for your investigation!

I have to say that getting this to work on MacOS has discouraged me somewhat in terms of forwards and backwards compatibility of OpenGL between operating systems.

**Comment by weigert** [comment]
closing issue
