### ISSUE TITLE
Switch from /usr/local/ to ~/.local

### ISSUE THREAD

**Issue by clort81** [weigert/TinyEngine#42]
A bit unusual that the project requires root priveleges.  Usually projects will build relative to the source tree in cwd.  An install is a seperate step to perform once any vetting / audit is complete.
The easiest way to avoid the sudo might be to switch target from /usr/local to $HOME/.local - at least on relatively modern linux.
the files to modify would be
```
$ grep -rl "/usr/local" *
examples/7.0_SDF/makefile
examples/13.0_Dither/makefile
examples/11.0_Voronoi/makefile
examples/19.1_LBM3D/makefile
examples/18.0_SphereVoronoi/makefile
examples/17.0_ODE3D/makefile
examples/8.0_Raymarch/makefile
examples/19.3_LBM3D/makefile
examples/4.0_Julia/makefile
examples/3.0_Automata/makefile
examples/0.0_Empty/makefile
examples/2.0_Heightmap/makefile
examples/1.0_Image/makefile
examples/.SlimeMold/makefile
examples/19.2_CollidingBalls/makefile
examples/5.0_Particles/makefile
examples/9.0_Scene/makefile
examples/10.0_Audio/makefile
examples/21.1_Delaunay_Divide/makefile
examples/12.0_Diffusion/makefile
examples/16.0_Gravity/makefile
examples/14.0_Renderpool/makefile
examples/0.1_Windowless/makefile
examples/21.0_Delaunay/makefile
examples/19.0_LBM2D/makefile
examples/20.0_Cloth/makefile
examples/15.0_Compute/makefile
examples/6.0_Tree/makefile
Makefile
python/setup_torch.py
python/setup.py
README.md
```
To change install target I ran:
```
find . -iname makefile -exec sed -i 's/\/usr\/local/\~\/.local/g' {} \;
```
To avoid errors caused by already-existing directories from previous run, i added "-p" to the mkdir
```
find . -iname makefile -exec sed -i 's/mkdir/mkdir \-p/g' {} \;
```
Then um, something something the linker needs to get pointed to ~/.local/lib without requiring overwriting of /etc/ld.so.cache  

Not sure what the right way to do that is, sorry.  
Maybe something like changing the link invocation
```
/TinyEngine/examples/0.0_Empty$ g++ -std=c++17 main.cpp -Wfatal-errors -O -I~/.local/include -L~/.local/lib/TinyEngine -lpthread -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lGLEW -lboost_system -lboost_filesystem -lX11 -lGL -o main
```

Cheers. Great project here.

**Comment by weigert** [comment]
Fixed in the latest release. Default install location has been moved, documentation has been updated.
