### ISSUE TITLE
Examples wont compile (except the empty example)

### ISSUE THREAD

**Issue by KamelOtmani** [weigert/TinyEngine#5]
Hi, I wanted to test the engine so I tried to compile the examples and they won't  because of the lambdas you are using, here is the image example when I try and compile it using g++ in manjaro (I'm pretty new to the Linux environment)

`In file included from main.cpp:5:
effects.h:9:25: error: non-local lambda expression cannot have a capture-default
    9 | Handle interfaceFunc = [&](){
      |                         ^
compilation terminated due to -Wfatal-errors.
`

**Comment by weigert** [comment]
Hi!

I have seen this error before, but I'm afraid I forgot exactly what the issue was... I think it depends on what your compiler allows / denies. Try changing the compiler flags to ignore fatal errors or use a later g++ compiler version? I suppose you are just using the makefile?

**Comment by m110h** [comment]
> 
> 
> Hi, I wanted to test the engine so I tried to compile the examples and they won't because of the lambdas you are using, here is the image example when I try and compile it using g++ in manjaro (I'm pretty new to the Linux environment)
> 
> `In file included from main.cpp:5: effects.h:9:25: error: non-local lambda expression cannot have a capture-default 9 | Handle interfaceFunc = [&](){ | ^ compilation terminated due to -Wfatal-errors. `

Hey. For avoid this issue you need include model.h to main.cpp directly. For example 5_Particles

`#include "../../TinyEngine.h"
#include "../../include/helpers/image.h"
#include "../../include/helpers/color.h"

const int WIDTH = 800;
const int HEIGHT = 800;

float zoom = 0.05;
float zoomInc = 0.001;
float rotation = 0.0f;
glm::vec3 cameraPos = glm::vec3(50, 50, 50);
glm::vec3 lookPos = glm::vec3(0, 0, 0);
glm::mat4 camera = glm::lookAt(cameraPos, lookPos, glm::vec3(0,1,0));
glm::mat4 projection;

void setup(){
  projection = glm::ortho(-(float)Tiny::view.WIDTH*zoom, (float)Tiny::view.WIDTH*zoom, -(float)Tiny::view.HEIGHT*zoom, (float)Tiny::view.HEIGHT*zoom, -800.0f, 500.0f);
};

int main( int argc, char* args[] ) {

	Tiny::window("Particle System", WIDTH, HEIGHT);
	
	Tiny::event.handler = [&](){

		if(Tiny::event.scroll.posy && zoom <= 0.3){
			zoom += zoomInc;
			projection = glm::ortho(-(float)WIDTH*zoom, (float)WIDTH*zoom, -(float)HEIGHT*zoom, (float)HEIGHT*zoom, -800.0f, 500.0f);
		}
		if(Tiny::event.scroll.negy && zoom > 0.005){
			zoom -= zoomInc;
			projection = glm::ortho(-(float)WIDTH*zoom, (float)WIDTH*zoom, -(float)HEIGHT*zoom, (float)HEIGHT*zoom, -800.0f, 500.0f);
		}
		if(Tiny::event.scroll.posx){
			rotation += 1.5f;
			if(rotation < 0.0) rotation = 360.0 + rotation;
			else if(rotation > 360.0) rotation = rotation - 360.0;
			camera = glm::rotate(camera, glm::radians(1.5f), glm::vec3(0.0f, 1.0f, 0.0f));
		}
		if(Tiny::event.scroll.negx){
			rotation -= 1.5f;
			if(rotation < 0.0) rotation = 360.0 + rotation;
			else if(rotation > 360.0) rotation = rotation - 360.0;
			camera = glm::rotate(camera, glm::radians(-1.5f), glm::vec3(0.0f, 1.0f, 0.0f));
		}

	};
	
	Tiny::view.interface = [&](){ /* ... */ }; //No Interface

	setup(); 												//Prepare Model Stuff

	Square3D model;									//Model we want to instance render!

	Particle particle(&model);			//Particle system based on this model
	for(int i = 0; i < 1000; i++){	//Generate random model matrices
		glm::mat4 model = glm::translate(glm::mat4(1.0),  glm::vec3(rand()%101-50, rand()%101-50, rand()%101-50));
		particle.models.push_back(glm::rotate(model, 2.0f*3.14159265f*(float)(rand()%360)/360.0f, glm::vec3(0.0, 1.0, 0.0)));
	}
	particle.update();							//Update particle system

	Texture tex(image::load("dot.png"));		//Texture to draw onto the model
	Shader particleShader({"shader/particle.vs", "shader/particle.fs"}, {"in_Quad", "in_Tex", "in_Model"});

	Tiny::view.pipeline = [&](){

		Tiny::view.target(color::black);

		particleShader.use();
		particleShader.texture("spriteTexture", tex);
		particleShader.uniform("projectionCamera", projection*camera);
		particle.render();

	};

	Tiny::loop([&](){ //Autorotate Camera
		camera = glm::rotate(camera, glm::radians(0.1f), glm::vec3(0.0f, 1.0f, 0.0f));
	});

	Tiny::quit();

	return 0;
}
`

**Comment by m110h** [comment]
hi again! I spent a little bit time for reading the code and understood. lambda functions uses only global variables. so, just transform [&] to []. it's a solve.

**Comment by qxzcode** [comment]
Is there a good reason for those to be defined as lambdas? Why not just declare them as plain-old named functions?

**Comment by weigert** [comment]
It is not strictly necessary. You could also use an std::function, or define a function pointer somewhere else. It just lets the program be nice and legible in a single file. The functions do need defining though, as they are not initialized as anything and the program won't run otherwise.

**Comment by aamott** [comment]
Hey! Just dropping in since I'm getting the same error. I am not sure I understand how I would switch from [&] to [], but I tried just replacing all occurrences in the example files I experimented with.  Is there something I am missing?
