### ISSUE TITLE
noise.h missing for heightmap example

### ISSUE THREAD

**Issue by meigel** [weigert/TinyEngine#9]
Trying to compile 2_Heightmap yields

g++ -std=c++17 main.cpp ../../include/imgui/imgui.cpp ../../include/imgui/imgui_demo.cpp ../../include/imgui/imgui_draw.cpp ../../include/imgui/imgui_widgets.cpp ../../include/imgui/imgui_impl_opengl3.cpp ../../include/imgui/imgui_impl_sdl.cpp -Wfatal-errors -O -I/usr/local/include -L/usr/local/lib -lX11 -lpthread -lSDL2 -lnoise -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lGL -lGLEW -lboost_serialization -lboost_system -lboost_filesystem -o main
In file included from main.cpp:4:0:
model.h:1:10: fatal error: noise/noise.h: No such file or directory
 #include "noise/noise.h"
          ^~~~~~~~~~~~~~~
compilation terminated.

(and as someone mentioned in another issue, -lnoise has to be removed from 5_Particles makefile)

**Comment by weigert** [comment]
Thanks for the issue.

This is a hidden dependency I forgot to include. The heightmap is generated using perlin noise from libnoise. You must install libnoise for the height map generation. You can also remove the dependency by removing that line and the flag in the linker and replacing the height map generation in "model.h" to whatever you like.

To fix, install libnoise: http://libnoise.sourceforge.net/

To workaround, edit "model.h".

If you are on > Ubuntu18, then libnoise is in a slightly different location (see issue here): https://github.com/weigert/territory/issues/15

**Comment by meigel** [comment]
Thanks for the hint! Also thanks for this nice little engine!
